// Generated by scripts/preprocess_sprites.py — do not edit.
// Sprite sizes and anchors, measured from the sprites themselves.
#pragma once
#include <nds.h>

// A building sprite: canvas size and the pixel that sits on the centre
// of the building's footprint diamond.
struct SpriteGeom { s16 w, h, ax, ay; };

// A unit sheet: cell size, the cell pixel of the unit's ground position,
// columns in the sheet, frames per direction, and whether the animation
// plays once (deaths) or loops.
struct SheetGeom { u8 cw, ch, ax, ay, cols, fpd; bool once; };

// Indexed by BuildingTypeId
static const SpriteGeom BLDG_GEOM[] = {
    { 136,  80,  68,  62 },  // town_center
    {  53,  39,  28,  24 },  // house
    {  97,  69,  49,  47 },  // barracks
    { 104,  86,  51,  62 },  // archery_range
    { 108,  68,  54,  45 },  // stable
    {   0,   0,   0,   0 },  // farm (terrain)
    {  57,  34,  28,  22 },  // mining_camp
    {  64,  43,  36,  29 },  // lumber_camp
    {  37,  34,  20,  26 },  // wall
    {  59,  67,  41,  61 },  // tower
    { 126, 104,  65,  74 },  // market
    { 146, 117,  86,  93 },  // castle
    { 119, 102,  72,  81 },  // monastery
    { 132,  81,  65,  53 },  // university
};

// Construction sites, indexed by footprint size - 1; the sheet holds
// 3 stages stacked vertically.
static const int CONSTRUCTION_STAGES = 3;
static const SpriteGeom CONSTRUCTION_GEOM[] = {
    {  33,  23,  18,  15 },  // 1x1
    {  59,  36,  31,  21 },  // 2x2
    {  90,  51,  47,  29 },  // 3x3
    { 119,  65,  62,  36 },  // 4x4
};

// Resource sheets (data/spr_res_*.bin): `count` variants side by side,
// each a cw x ch cell with (ax, ay) on the centre of its tile.
struct ResGeom { u8 cw, ch, ax, ay, count; };
static const ResGeom RES_GEOM_tree = { 48, 67, 24, 57, 14 };
static const ResGeom RES_GEOM_gold = { 29, 17, 13, 7, 7 };
static const ResGeom RES_GEOM_stone = { 28, 17, 14, 12, 7 };
static const ResGeom RES_GEOM_berries = { 30, 22, 16, 16, 4 };

// Unit sheets, named after their data/spr_*.bin
static const SheetGeom GEOM_villager = { 8, 14, 5, 13, 5, 5, false };
static const SheetGeom GEOM_villager_walk = { 8, 15, 5, 13, 10, 10, false };
static const SheetGeom GEOM_villager_attack = { 20, 16, 13, 13, 10, 10, false };
static const SheetGeom GEOM_villager_carry = { 11, 18, 6, 15, 10, 5, false };
static const SheetGeom GEOM_villager_die = { 26, 24, 7, 14, 10, 10, true };
static const SheetGeom GEOM_lumberjack = { 11, 17, 6, 15, 5, 5, false };
static const SheetGeom GEOM_lumberjack_walk = { 14, 16, 8, 13, 10, 10, false };
static const SheetGeom GEOM_lumberjack_work = { 23, 23, 16, 16, 10, 10, false };
static const SheetGeom GEOM_lumberjack_carry = { 11, 15, 7, 13, 10, 5, false };
static const SheetGeom GEOM_miner = { 11, 14, 6, 12, 5, 5, false };
static const SheetGeom GEOM_miner_walk = { 15, 15, 8, 13, 10, 10, false };
static const SheetGeom GEOM_miner_work = { 23, 18, 14, 12, 10, 10, false };
static const SheetGeom GEOM_miner_carry = { 9, 15, 4, 13, 10, 5, false };
static const SheetGeom GEOM_builder = { 7, 15, 4, 13, 5, 5, false };
static const SheetGeom GEOM_builder_walk = { 9, 16, 6, 13, 10, 10, false };
static const SheetGeom GEOM_builder_work = { 17, 17, 12, 11, 10, 10, false };
static const SheetGeom GEOM_farmer = { 11, 19, 6, 16, 5, 5, false };
static const SheetGeom GEOM_farmer_walk = { 13, 18, 6, 16, 10, 10, false };
static const SheetGeom GEOM_farmer_work = { 26, 28, 20, 22, 10, 10, false };
static const SheetGeom GEOM_farmer_carry = { 11, 18, 6, 15, 10, 5, false };
static const SheetGeom GEOM_forager_carry = { 11, 16, 6, 13, 10, 5, false };
static const SheetGeom GEOM_militia = { 12, 16, 6, 13, 5, 5, false };
static const SheetGeom GEOM_militia_walk = { 10, 16, 6, 13, 10, 10, false };
static const SheetGeom GEOM_militia_fight = { 20, 22, 11, 17, 10, 10, false };
static const SheetGeom GEOM_militia_die = { 38, 26, 18, 15, 10, 10, true };
static const SheetGeom GEOM_archer = { 15, 17, 9, 13, 5, 5, false };
static const SheetGeom GEOM_archer_walk = { 15, 17, 8, 13, 10, 10, false };
static const SheetGeom GEOM_archer_fire = { 17, 21, 9, 17, 10, 10, false };
static const SheetGeom GEOM_archer_die = { 45, 33, 21, 21, 10, 10, true };
static const SheetGeom GEOM_knight = { 28, 29, 12, 23, 5, 5, false };
static const SheetGeom GEOM_knight_walk = { 26, 28, 13, 22, 10, 10, false };
static const SheetGeom GEOM_knight_fight = { 24, 31, 12, 25, 10, 10, false };
static const SheetGeom GEOM_knight_die = { 40, 29, 20, 21, 10, 10, true };
static const SheetGeom GEOM_spearman = { 20, 21, 11, 18, 5, 5, false };
static const SheetGeom GEOM_spearman_walk = { 22, 20, 12, 16, 10, 10, false };
static const SheetGeom GEOM_spearman_fight = { 29, 29, 21, 17, 10, 10, false };
static const SheetGeom GEOM_spearman_die = { 35, 32, 23, 19, 10, 10, true };
static const SheetGeom GEOM_scout = { 29, 30, 15, 22, 5, 5, false };
static const SheetGeom GEOM_scout_walk = { 27, 29, 13, 22, 10, 10, false };
static const SheetGeom GEOM_scout_fight = { 25, 30, 15, 23, 10, 10, false };
static const SheetGeom GEOM_scout_die = { 35, 31, 18, 22, 10, 10, true };
static const SheetGeom GEOM_sheep_stand = { 13, 12, 9, 8, 5, 5, false };
static const SheetGeom GEOM_sheep_walk = { 14, 12, 9, 8, 10, 10, false };
static const SheetGeom GEOM_sheep_die = { 17, 13, 10, 8, 10, 10, true };
static const SheetGeom GEOM_ram_stand = { 33, 29, 17, 21, 5, 1, false };
static const SheetGeom GEOM_ram_walk = { 33, 29, 17, 21, 10, 10, false };
static const SheetGeom GEOM_ram_fight = { 35, 30, 19, 21, 10, 10, false };
static const SheetGeom GEOM_ram_die = { 48, 33, 23, 21, 10, 10, true };
static const SheetGeom GEOM_mango_stand = { 33, 27, 16, 16, 5, 1, false };
static const SheetGeom GEOM_mango_walk = { 34, 27, 17, 16, 10, 10, false };
static const SheetGeom GEOM_mango_fight = { 37, 30, 21, 18, 10, 10, false };
static const SheetGeom GEOM_mango_die = { 42, 30, 19, 16, 10, 10, true };
static const SheetGeom GEOM_monk_stand = { 10, 17, 7, 15, 5, 5, false };
static const SheetGeom GEOM_monk_walk = { 11, 19, 7, 15, 10, 10, false };
static const SheetGeom GEOM_monk_fight = { 17, 22, 9, 18, 10, 10, false };
static const SheetGeom GEOM_monk_die = { 40, 30, 24, 17, 10, 10, true };
